### ISSUE TITLE
Lockfile consistency

### ISSUE THREAD

**Issue by benlangfeld** [powerhome/power-tools#97]
Some packages have a `Gemfile.lock` checked in, other have it ignored. Is this intentional? It seems that we are lacking consistency here.

**Comment by xjunior** [comment]
@benlangfeld they shouldn't have the Gemfile.lock checked in so we can test them against multiple versions of some gems (bundler or rails).

**Comment by benlangfeld** [comment]
@xjunior The argument in the community has switched toward checking in `Gemfile.lock` more recently, arguing that the dependencies used in CI and by a fresh checkout of the project should be known good, and that upgrades should be explicit (by Renovate in our case) so that we can identify clearly the source of breakage (CI failing on Renovate PRs).

I'm actually in favour of checking in all `Gemfile.lock` files and explicitly working around them where you want to vary versions of bundler/rails/etc. Thoughts?

**Comment by xjunior** [comment]
@benlangfeld I'm not that convinced of the benefits, as the `gemspec` still references the known supported versions. Having multiple Gemfile.lock files makes maintenance a lot harder, specially in a matrix with `bundler` and `rails` variations.
